apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-frontend-deployment

spec:
  selector:
    matchLabels: 
      app: nginx-frontend

  template: # Pod template - cut & paste from 01-pod-definition.yaml from kube-manifests pod (from )
    metadata: # Dictionary
      name: nginx-frontend-pod
      labels: # Dictionary
        app: nginx-frontend
    spec:
      containers: # List
      - name: nginx-frontend
        image: simpleregrepo.azurecr.io/ngnix-frontend:v6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80