# this is the same as kubectl expose
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-frontend
  ports:
  - name: http
    port: 80 # Serice port
    targetPort: 80 # Container Port
