apiVersion: v1 #String
kind: Pod # String
metadata: # Dictionary
  name: nodejs-backend-pod
  labels: # Dictionary
    app: nodejs-backend
spec:
  containers: # List
  - name: nodejs-backend
    image: simpleregrepo.azurecr.io/nodejs-backend:v4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080