# this is the same as kubectl expose
apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs-backend
  ports:
  - name: http
    port: 80 # Serice port
    targetPort: 8080 # Container Port
